### ISSUE TITLE
Remove `spirv-builder` as a dependency

### ISSUE THREAD

**Issue by schell** [Rust-GPU/cargo-gpu#1]
Having `spirv-builder` in the build tree requires that `cargo-gpu` be built with a specific nightly. 

Ideally `cargo-gpu` could be installed from crates.io and would build `spirv-builder` and `rustc_codegen_spirv` into another binary stored somewhere in the cache directory (currently `~/.rust-gpu`) with a good prefix. It could then manage a small set of these binaries for special cases, like working with a pinned nightly channel or hacking on `rust-gpu` itself.

**Comment by LegNeato** [comment]
Is there any way we can hook into rustup? We are kinda a component like miri or llvm-tools 🤔

**Comment by schell** [comment]
I'm not sure, but I'll look into it.

**Comment by schell** [comment]
No luck and figuring out how components are done with `rustup`, but I did decouple `spirv-builder` from `cargo-gpu`.
