### ISSUE TITLE
Odd inconsequential "invalid string" error when running `cargo install`

### ISSUE THREAD

**Issue by schell** [Rust-GPU/cargo-gpu#17]
It seems that when running "cargo install" the `spirv-builder-cli` project is causing `cargo` to barf a little. It doesn't affect the installation but it doesn't look good.

```
❯ cargo install --git https://github.com/rust-gpu/cargo-gpu 
    Updating git repository `https://github.com/rust-gpu/cargo-gpu`
error: invalid string
expected `"`, `'`
  --> ../../.cargo/git/checkouts/cargo-gpu-ed3d64cbb28dfcbe/f46e031/crates/spirv-builder-cli/Cargo.toml:15:17
   |
15 | spirv-builder = ${SPIRV_BUILDER_SOURCE}
   |                 ^
   |
warning: profiles for the non root package will be ignored, specify profiles at the workspace root:
package:   /Users/schell/.cargo/git/checkouts/cargo-gpu-ed3d64cbb28dfcbe/f46e031/crates/cargo-gpu/Cargo.toml
workspace: /Users/schell/.cargo/git/checkouts/cargo-gpu-ed3d64cbb28dfcbe/f46e031/Cargo.toml
```

I don't know why it's inspecting `crates/spirv-builder-cli` as it's specifically ignored in the top-level Cargo.toml.

**Comment by mbernat** [comment]
I tried addressing this by making `spirv-builder-cli` a proper package that is part of the workspace. I didn't quite succeed but at least `cargo` told me why it's complaining.

```
chill@Mac shader-crate-template % cargo install --git https://github.com/mbernat/cargo-gpu --rev 9179746a2e2cab76c07e1771b59d9ba3ff1b3183
    Updating git repository `https://github.com/mbernat/cargo-gpu`
error: multiple packages with binaries found: cargo-gpu, spirv-builder-cli. When installing a git repository, cargo will always search the entire repo for any Cargo.toml.
Please specify a package, e.g. `cargo install --git https://github.com/mbernat/cargo-gpu cargo-gpu`.
chill@Mac shader-crate-template % cargo install --git https://github.com/mbernat/cargo-gpu --rev 9179746a2e2cab76c07e1771b59d9ba3ff1b3183 cargo-gpu
```

The suggestion to specify a package resolves this particular issue in my approach but unfortunately it doesn't help with your original problem, `cargo` eagerly scans the whole repo anyway.

**Comment by mbernat** [comment]
I suppose the simplest solution would be to assemble the whole `spirv-builder-cli` package from text files that are opaque to Cargo, at least if one can survive the maintainability hit.

My unfinished approach in https://github.com/mbernat/cargo-gpu/tree/fix-invalid-string-error would make things a bit easier to maintain but it has downsides of its own.
- Haven't gotten it to work yet, maybe it's not even possible.
- I had to create a dummy `spirv-builder` package that `spirv-builder-cli` can interface with. The dummy would need to be kept updated with the upstream `spirv-builder`. That being said, this problem exists already: it would just manifest when trying to install `spirv-builder` with incompatible API.

**Comment by schell** [comment]
@mbernat thanks for trying that. Having the `spirv-builder-cli` as text files is a good suggestion. Thanks!

**Comment by schell** [comment]
This is no longer happening on `main`.
