### ISSUE TITLE
Investigate `rustup component` for `cargo-gpu`

### ISSUE THREAD

**Issue by schell** [Rust-GPU/cargo-gpu#2]
It would be great to be able to `rustup component add spirv-builder-cli` or something similar...

**Comment by LegNeato** [comment]
I was thinking maybe the opposite might be easier (as I bet the components come from a central rust project place we wouldn't have access to). To use rustup as a library, wrap it, or soft fork it. So all the plumbing and ux is taken care of for us and later going in rustup proper is easy.

**Comment by LegNeato** [comment]
Some docs I found:

https://forge.rust-lang.org/infra/channel-layout.html

**Comment by LegNeato** [comment]
Looks like `RUSTUP_DIST_SERVER` enables overriding where rustup looks

**Comment by schell** [comment]
Ok, I see. I think getting our own binary distribution service would be a better user experience, but that's quite a big lift. Also `rustup` feels pretty large! I think we can get away with _much_ less.

**Comment by LegNeato** [comment]
You might want to look into how [rustc-perf uses it](https://github.com/rust-lang/rustc-perf/tree/master/collector#how-to-benchmark-a-change-on-your-own-machine)...the tool obviously doesn't expose all rustup but it uses the plumbing, which I think is roughly what we need (plus some special sauce on top). I also don't think we need a distribution service, I think we can use github releases or a static repo 🤷‍♂️

Maybe it is not the right solution, but I'd hate to roll and maintain our own if we can leverage what is there if at all possible.

**Comment by schell** [comment]
After looking at that, I think it would actually be _more work_ to use the `rustup` machinery. All we need is a cache directory and some deterministic prefixes.

I'm still in favor of this if it turns out that the current solution is untenable, for whatever reason, but for now I think this is a non-issue.
