### ISSUE TITLE
Use optional [package.metadata.rust-gpu] in Cargo.toml

### ISSUE THREAD

**Issue by schell** [Rust-GPU/cargo-gpu#6]
To make it easier for projects to use `cargo-gpu` and since there are a good number of options to remember, maybe we should allow the use of an option cargo-gpu.toml file?

Something like this:

```
[build]
shader-crate = "crates/renderling"
output-dir = "crates/renderling/shaders"
shader-manifest = "crates/renderling/shaders/manifest.json"
```

**Comment by schell** [comment]
Nope! It's actually easy to set this up by hand with a cargo alias in `.cargo/config.toml`: 

```
[alias]
shaders = "gpu build --output-dir crates/renderling/shaders --shader-crate crates/renderling/ --shader-manifest crates/renderling/shaders/manifest.json"
```

**Comment by tombh** [comment]
I don't think `.cargo/config.toml` can be relied on to be committed to a project? For example I keep some project-specific, personal preferences in there.

What about a `[package.metadata.rust-gpu]` section in `Cargo.toml`? The `pacakge.metadata` namespace is ignored by `cargo`, so it's safe to use.

**Comment by LegNeato** [comment]
Yep, we had previously discussed this in https://github.com/EmbarkStudios/rust-gpu/issues/1137#issuecomment-1973729786

**Comment by schell** [comment]
Ok, I'll work on this.
